name: Deploy to the server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build code
        run: |
          # Run your build commands here
           npm run build

      - name: Check build status and deploy
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: 89.116.52.59
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/privatechefsworl
            bash deploy.sh
